import type { Metadata } from "next";
import { Luxurious_Roman, Quicksand } from "next/font/google";
import "./globals.css";
import Header from "./components/NavBar";
import Footer from "./components/Footer/Footer";

export const luxuriousRoman = Luxurious_Roman({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-luxurious-roman",
});

export const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"],
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "Let There Be Fragrance",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.variable} ${luxuriousRoman.variable} antialiased`}
      >
        <div className="absolute top-0 left-0 w-full">
          <Header />
        </div>

        {children}

      <Footer />
      </body>
    </html>
  );
}
