import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Luxurious_Roman, Quicksand } from "next/font/google";
import "./globals.css";


// Importing Luxurious Roman and Quicksand fonts
const luxuriousRoman = Luxurious_Roman({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-luxurious-roman",
});

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"], 
});

// Importing Geist and Geist Mono fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${luxuriousRoman.variable} ${quicksand.variable} antialiased`}>
  {children}
</body>
    </html>
  );
}
